apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- hpa.yaml
- service.yaml
- ../../base
namespace: staging
images:
- name: vfarcic/silly-demo
  newName: vfarcic/silly-demo
  newTag: 1.0.0
